DIR=/home/aiden/.config/wallpaper/Dynamic_Wallpapers/DesertSands
# Format: StartHour|EndHour|ImageName
06|10|DesertSands-1.png
10|14|DesertSands-2.png
14|18|DesertSands-3.png
18|21|DesertSands-4.png
21|06|DesertSands-5.png
